# Docker Compose file for development

version: '3'
services:
  app:
    build:
      context: ./
      args:
        NODE_ENV: development
    command: npm run start:dev
    restart: always
    ports:
      - 4200:4200
    volumes:
      - ./.utils/:/opt/app/.utils/
      - ./packages/client/src/:/opt/app/packages/client/src/
      - ./packages/server/src/:/opt/app/packages/server/src/
